### PR TITLE
Added 4x4 tiger/antelope value iteration example

### PR DESCRIPTION
**Pull request by aukejw**
I added a Python example mimicking the tiger/antelope example in the documentation.

It has a drawing function for the gridworld for debugging purposes. As I use the `os.getcwd()` trick you also use in the tests, this file should be run from the directory where `MDP.so` is located or alternatively `MDP.so` should be in the pythonpath.

Output shows the policy for sample game states:

```
$ python ../examples/Python/tiger_antelope.py 
Converged: False

Policy for coord (0, 0, 1, 1)
=============================
y \ x  0    1    2    3   
 0   | T  |    |    |    |
 1   |    | A  |    |    |
 2   |    |    |    |    |
 3   |    |    |    |    |
  ACTION 'stand' , policy(a | s)=0.0
  ACTION 'up' , policy(a | s)=0.0
  ACTION 'down' , policy(a | s)=0.5
  ACTION 'left' , policy(a | s)=0.0
  ACTION 'right' , policy(a | s)=0.5

Policy for coord (0, 0, 2, 2)
=============================
y \ x  0    1    2    3   
 0   | T  |    |    |    |
 1   |    |    |    |    |
 2   |    |    | A  |    |
 3   |    |    |    |    |
  ACTION 'stand' , policy(a | s)=0.0
  ACTION 'up' , policy(a | s)=0.25
  ACTION 'down' , policy(a | s)=0.25
  ACTION 'left' , policy(a | s)=0.25
  ACTION 'right' , policy(a | s)=0.25

Policy for coord (0, 0, 3, 3)
=============================
y \ x  0    1    2    3   
 0   | T  |    |    |    |
 1   |    |    |    |    |
 2   |    |    |    |    |
 3   |    |    |    | A  |
  ACTION 'stand' , policy(a | s)=0.0
  ACTION 'up' , policy(a | s)=0.5
  ACTION 'down' , policy(a | s)=0.0
  ACTION 'left' , policy(a | s)=0.5
  ACTION 'right' , policy(a | s)=0.0

Policy for coord (1, 1, 1, 2)
=============================
y \ x  0    1    2    3   
 0   |    |    |    |    |
 1   |    | T  |    |    |
 2   |    | A  |    |    |
 3   |    |    |    |    |
  ACTION 'stand' , policy(a | s)=0.0
  ACTION 'up' , policy(a | s)=0.0
  ACTION 'down' , policy(a | s)=1.0
  ACTION 'left' , policy(a | s)=0.0
  ACTION 'right' , policy(a | s)=0.0
```

### CODE REVIEW

**Comment by Svalorzen** [comment]
Bunch of suggestions:

- Add an explanation of what the test is (even copying the one from the other example file is fine). This is to avoid someone opening just the example and not understanding anything in it.
- Make the example runnable from the example folder, given that someone has already built the project in a `build` folder (see the cpp example makefile). This is consistent with the example, and I feel makes a bit more sense. Best would be that if the import fails from the example folder, it spits out a message that says that it cannot find the build folder, but not strictly necessary.
- I'm not 100% familiar with python, so I don't know whether now `numpy` is bundled with python or not, but in case it's not maybe it would be nice to keep it out of the requirements. Or maybe for a project like this numpy is nearly expected. I have no idea.

**Comment by aukejw** [comment]
On your suggestions:

* Agreed, added a few comments.
* If the filestructure remains the same or MDP is already in the pythonpath, the example should now be runnable from anywhere. I'll stresstest this a bit and improve the message a bit.
* Removed the (unnecessary) numpy dep, was actually only used for debugging purposes.

**Comment by aukejw** [comment]
@Svalorzen I've tried to see if the value function given by the cpp tutorial and this python script are identical for the same set of parameters (epsilon, horizon, square size), but I can't find a corresponding class in the documenation. 

Is there a `ValueFunction` class, like there is a `Policy` class, that allows me to retrieve the values for each state? And if not, how would I go about reading the entries in the tuple (`MDP.Vector` and `MDP.size_t`)?

**Comment by Svalorzen** [comment]
Yeah, in Cpp the ValueFunction is simply a tuple of two vectors: the values for each state and the best actions to perform in those states.

MDP.Vector is simply an array. If you do `help(MDP.Vector)` you'll see that it implements `__getitem__` and `__setitem__`. So you can just use square brackets to read/write from it.

`size_t` should be just an int type, do you have problems in reading it?

(I'll add a `__len__` method so you can also do `len(vector)` ASAP)

**Comment by Svalorzen** [comment]
Done. Example code now:

    >>> import MDP
    >>> x = MDP.Vector(15)
    >>> len(x)
    15
    >>> x[0] = 14.3
    >>> x[0]
    14.3

And

    >>> import MDP
    >>> x = MDP.Matrix2D(4,5)
    >>> x.shape()
    (4, 5)
    >>> x[1,2] = 7
    >>> x[1,2]
    7.0

**Comment by Svalorzen** [comment]
Merged! (at last)

**Pull request closed without merging**
